/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kt.lib

class App {
    var sumResult = 0
}

fun main() {
    System.loadLibrary("jni_example")
    val plugin = Plugin()
    val app = plugin.createApp()
    val result = plugin.sum(List(10) { index ->
        index + 1
    })
    plugin.setResult(result)
    println("sum result is ${app.sumResult}")
}
