/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kt.lib

import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test fun appHasAGreeting() {
        val classUnderTest = App()
        assertNotNull(classUnderTest.sumResult, "app should have a sumResult")
    }
}
